"""empty message

Revision ID: 047859bf8d28
Revises: 5f5a817573ac
Create Date: 2023-09-15 11:38:11.413620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047859bf8d28'
down_revision: Union[str, None] = '5f5a817573ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('read', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mails', 'read')
    # ### end Alembic commands ###
