"""test

Revision ID: 5b81991ca5c0
Revises: 658cbe2d350c
Create Date: 2023-08-30 06:18:45.210040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b81991ca5c0'
down_revision: Union[str, None] = '658cbe2d350c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('mail_id', sa.Integer(), nullable=True))
    op.alter_column('mails', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'mails', 'topics', ['mail_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mails', type_='foreignkey')
    op.alter_column('mails', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('mails', 'mail_id')
    # ### end Alembic commands ###
