"""test

Revision ID: 6c3e94e6b979
Revises: 5b81991ca5c0
Create Date: 2023-08-30 06:20:34.460318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3e94e6b979'
down_revision: Union[str, None] = '5b81991ca5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('its_answer', sa.Boolean(), nullable=False))
    op.drop_constraint('mails_mail_id_fkey', 'mails', type_='foreignkey')
    op.create_foreign_key(None, 'mails', 'mails', ['mail_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mails', type_='foreignkey')
    op.create_foreign_key('mails_mail_id_fkey', 'mails', 'topics', ['mail_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mails', 'its_answer')
    # ### end Alembic commands ###
