"""empty message

Revision ID: a1d0099ffbc7
Revises: f160c577106a
Create Date: 2023-09-12 06:02:21.362830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d0099ffbc7'
down_revision: Union[str, None] = 'f160c577106a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answers_topic_id_fkey', 'answers', type_='foreignkey')
    op.drop_column('answers', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('answers_topic_id_fkey', 'answers', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
