"""empty message

Revision ID: b6a8899e2026
Revises: 6c3e94e6b979
Create Date: 2023-09-11 16:32:41.209716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a8899e2026'
down_revision: Union[str, None] = '6c3e94e6b979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mails_mail_id_fkey', 'mails', type_='foreignkey')
    op.drop_column('mails', 'its_answer')
    op.drop_column('mails', 'mail_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('mail_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mails', sa.Column('its_answer', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('mails_mail_id_fkey', 'mails', 'mails', ['mail_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
