version: '3.8'

services:
  backend_server:
    build: ./backend_server
    ports:
      - ${BACKEND_SERVER__PORT}:${BACKEND_SERVER__PORT}
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend_server/alembic/versions:/app/alembic/versions/
    networks:
      - anocat
  file_server:
    build: ./file_server
    ports:
      - ${FILE_SERVER__PORT}:${FILE_SERVER__PORT}
    env_file:
      - .env
    volumes:
      - ./file_server/files/:/app/files/
    networks:
      - anocat
  db:
    image: postgres:15
    command: postgres -c listen_addresses='*'
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks:
      - anocat

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - anocat
volumes:
  postgres-data:
networks:
  anocat:
    name: anocat-default