version: '3.8'

services:
  app:
    build: ./app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app/alembic/versions:/app/alembic/versions/
  db:
    image: postgres:15
    command: postgres -c listen_addresses='*'
    restart: always
    env_file:
      - .env
    # ports:
    #   - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  postgres-data: